config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :articles
  resources :subscribers, only: [:index, :new, :create] do
    get :verify, on: :collection
    get :unsubscribe, on: :collection
  end

  resources :subscription_plans, only: [:create, :update, :edit]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'admin', to: 'admin#index'
  get 'admin/edit_config/:id', to: 'admin#edit', as: :edit_config
  put 'admin/edit_config/:id', to: 'admin#update'
  patch 'admin/edit_config/:id', to: 'admin#update'

  get 'p/:slug', to: 'articles#permalink', as: :permalink

  root to: 'subscribers#new'
end

app/models/app_config.rb
class AppConfig < ApplicationRecord
  enum data_type: { string: 'string', integer: 'integer', boolean: 'boolean' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates_uniqueness_of :slug

  before_create :generate_slug
  after_create :schedule_to_send

  def generate_slug
    self.slug = self.title.parameterize
  end

  def schedule_to_send
    Subscriber.currently_subscribed.find_each do |subscriber|
      ArticleMailer.with(article_id: self.id, subscriber_id: subscriber.id).new_article_email.deliver_later
    end
  end
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates :email, presence: true, uniqueness: { case_sensitive: false }

  before_save :sanitize_email
  before_create :generate_tokens

  scope :verified, -> { where(verified: true) }
  scope :currently_subscribed, -> { where(verified: true, unsubscribed: false) }

  def sanitize_email
    self.email = self.email.strip 
  end

  def verified?
    self.verified
  end

  def subscribed?
    !self.unsubscribed
  end

  def generate_tokens
    begin
      self.verification_token = SecureRandom.hex 32
    end while Subscriber.where(verification_token: self.verification_token).exists?

    begin
      self.unsubscription_token = SecureRandom.hex 32
    end while Subscriber.where(unsubscription_token: self.unsubscription_token).exists?
  end
end

app/models/subscription_plan.rb
class SubscriptionPlan < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable, :trackable#, :confirmable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!

  def index
    @app_configs = AppConfig.all
    @subscription_plans = SubscriptionPlan.all
  end

  def edit
    @app_config = AppConfig.find params[:id]
  end

  def update
    @app_config = AppConfig.find params[:id]
    if @app_config.update app_config_params
      redirect_to admin_path, notice: 'Configuration updated successfully.'
    else
      render :edit, alert: 'Please try updating again.'
    end
  end

  private

  def app_config_params
    params.require(:app_config).permit(:value)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def permalink
    slug = params[:slug]
    @article = Article.find_by_slug slug
    render :show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  def index
  end

  def new
    @subscriber = Subscriber.new
  end

  def create
    if subscriber = Subscriber.where("lower(email) = lower('#{subscriber_params[:email]}')").first

      if subscriber.verified? && subscriber.subscribed?
        redirect_to root_url, notice: "You're already on the list."

        return
      end

      subscriber.generate_tokens
      subscriber.unsubscribed = false
      subscriber.verified = false
      SubscriberMailer.with(email: subscriber.email, token: subscriber.verification_token).verify.deliver_later
      if subscriber.save
        redirect_to root_url, notice: "Please verify your email address by clicking on the link we've sent you in the mail."
      else
        redirect_to root_url, alert: "We were not able to save your email."
      end

      return
    end

    @subscriber = Subscriber.new subscriber_params

    if @subscriber.save
      SubscriberMailer.with(email: @subscriber.email, token: @subscriber.verification_token).verify.deliver_later
      redirect_to root_url, notice: "Please verify your email address by clicking on the link we've sent you in the mail."
    else
      redirect_to root_url, alert: "We were not able to save your email."
    end
  end

  def verify
    token = params[:token]
    email = params[:email]
    subscriber = Subscriber.find_by_verification_token! token
    if subscriber.email.downcase == email.downcase.strip
      subscriber.update verified: true
    else
      render plain: "Couldn't verify your email."
    end
  end

  def unsubscribe
    token = params[:token]
    email = params[:email]
    subscriber = Subscriber.find_by_unsubscription_token! token
    if subscriber.email.downcase == email.downcase.strip
      subscriber.update unsubscribed: true
    else
      render plain: "Couldn't unsubscribe your email."
    end
  end

  private

  def subscriber_params
    params.require(:subscriber).permit(:email)
  end
end

app/controllers/subscription_plans_controller.rb
class SubscriptionPlansController < ApplicationController
  before_action :authenticate_user!
  
  def update
    @subscription_plan = SubscriptionPlan.find params[:id]
    if @subscription_plan.update subscription_plan_params
      redirect_to admin_path, notice: 'Subscription plan updated successfully.'
    else
      redirect_to admin_path, alert: 'There was a problem updating your subscription plan. Please try again.'
    end
  end

  def edit
    @subscription_plan = SubscriptionPlan.find params[:id]
  end

  private

  def subscription_plan_params
    params.require(:subscription_plan).permit(:name, :base_currency, :monthly_rate, :annual_rate)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def site_title
    @config ||= AppConfig.where(key: 'title').first
    if @config
      @config.value
    else
      'AgentK'
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/helpers/subscription_plans_helper.rb
module SubscriptionPlansHelper
end

app/views/admin/edit.html.haml
.row
  .col-md-8.offset-md-2
    %h2 Editing - #{@app_config.key}
    = form_with model: @app_config, url: edit_config_path(@app_config) do |f|
      .form-group
        = f.label :value
        = f.text_field :value, class: 'form-control'
      = f.submit 'Save', class: 'btn btn-success'

app/views/admin/index.html.haml
.row
  .col-lg-8.offset-lg-2
    %h1 Admin
    %hr/
    %h3
      App Config

    %table.table
      %thead
        %tr
          %th Key
          %th Value
          %th Data Type
          %th
      %tbody
        - @app_configs.each do |config|
          %tr
            %td= config.key
            %td= config.value
            %td= config.data_type
            %td= link_to 'Edit', edit_config_path(config)
    %h3
      Subscription Plans

    %table.table
      %thead
        %tr
          %th Name
          %th.text-right Base Currency
          %th.text-right Monthly Rate
          %th.text-right Annual Rate
          %th
      %tbody
        - @subscription_plans.each do |plan|
          %tr
            %td= plan.name
            %td.text-right= plan.base_currency
            %td.text-right= plan.monthly_rate
            %td.text-right= plan.annual_rate
            %td= link_to "Edit", edit_subscription_plan_path(plan)

app/views/articles/_form.html.haml
= form_for @article do |f|
  - if @article.errors.any?
    #error_explanation
      %h2= "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
      %ul
        - @article.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.text_field :title, class: "form-control", placeholder: "Title"
  .form-group
    = f.hidden_field :body, id: :post_body, class: "form-control"
    %trix-editor#post-body-editor{ input: "post_body", placeholder: "Article Body" }
  .actions
    = f.submit 'Save', class: "btn btn-success float-right"

app/views/articles/edit.html.haml
.row
  .col-md-8.offset-md-2
    %h2 Edit article
    %hr/

    = render 'form'

    = link_to 'Show', @article
    \|
    = link_to 'Back', articles_path

app/views/articles/index.html.haml
.row
  .col-md-8.offset-md-2
    %h1
      Your Articles
      = link_to 'New Article', new_article_path, class: "btn btn-sm btn-primary" if user_signed_in?
    %hr/

    %ul.list-group
      - @articles.each do |article|
        %li.list-group-item
          = link_to article.title, article
          %span.float-right{ title: article.created_at.strftime("%b %d, %Y %H:%M:%S") }= article.created_at.strftime("%b %d")

app/views/articles/new.html.haml
.row
  .col-md-8.offset-md-2
    %h2 New article
    %hr/

    = render 'form'

    = link_to 'Back', articles_path

app/views/articles/show.html.haml
- content_for :title do
  = @article.title
.row
  .col-md-8.offset-md-2
    %h1= @article.title
    %hr/
    = simple_format @article.body
    .float-right
      = link_to 'Permalink', permalink_path(slug: @article.slug)
      - if user_signed_in?
        \|
        = link_to 'Edit', edit_article_path(@article)
        \|
        = link_to 'Delete', @article, method: :delete, data: { confirm: 'Are you sure?' }
      \|
      = link_to 'Back', articles_path

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-dark.bg-primary
  %a.navbar-brand.mb-0.h1{ href: "/" }= site_title
  %button.navbar-toggler{ type: "button", "data-toggle": "collapse", "data-target": "#navbarNav", "aria-controls": "navbarNav", "aria-expanded": "false", "aria-label": "Toggle navigation" }
    %span.navbar-toggler-icon
  .collapse.navbar-collapse#navbarNav
    %ul.navbar-nav
      - if user_signed_in?
        %li.nav-item
          = link_to 'Admin', admin_path, class: 'nav-link'
        %li.nav-item
          = link_to 'Articles', articles_path, class: 'nav-link'
        %li.nav-item
          = link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link'
      - else
        %li.nav-item
          = link_to 'Sign In', new_user_session_path, class: 'nav-link'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title
      = yield(:title).presence || site_title
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/navbar'
    .container-fluid
      - if notice
        .row
          .col-lg-8.offset-lg-2
            .alert.alert-success.mt-3{ role: 'alert' }
              = notice
              %button.close{ type: "button", "data-dismiss" => "alert", "aria-label" => "Close" }
                %span{ "aria-hidden" => "true"} &times;
      - if alert
        .row
          .col-lg-8.offset-lg-2
            .alert.alert-danger.mt-3{ role: 'alert' }
              = alert
              %button.close{ type: "button", "data-dismiss" => "alert", "aria-label" => "Close" }
                %span{ "aria-hidden" => "true"} &times;
      = yield

app/views/subscribers/create.html.haml
%h1 Subscribers#create
%p Find me in app/views/subscribers/create.html.haml

app/views/subscribers/index.html.haml
%h1 Subscribers#index
%p Find me in app/views/subscribers/index.html.haml

app/views/subscribers/new.html.haml
.row
  .col-lg-4.offset-lg-4
    = form_with model: @subscriber, class: "form-inline mt-5" do |f|
      = f.label :email, "What's your email?", style: 'font-size: 2rem;', class: 'text-center w-100'
      .input-group.mt-3.w-100
        = f.text_field :email, class: "form-control"
        .input-group-append
          = f.submit 'Subscribe!', class: 'btn btn-success'

app/views/subscribers/unsubscribe.html.haml
.row
  .col-md-8.offset-md-2
    %h1.text-center Your email has been unsubscribed!

app/views/subscribers/verify.html.haml
.row
  .col-md-8.offset-md-2
    %h1.text-center Your email has been verified!

app/views/subscription_plans/edit.html.haml
.row
  .col-md-8.offset-md-2
    %h2 Editing - #{@subscription_plan.name}
    = form_with model: @subscription_plan do |f|
      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control'
      .form-group
        = f.label :base_currency
        = f.select :base_currency, Money::Currency.all.map {|e| ["#{e.name} - #{e.iso_code}", e.iso_code] }, {}, class: 'form-control'
      .form-group
        = f.label :monthly_rate
        = f.number_field :monthly_rate, step: :any, class: 'form-control'
      .form-group
        = f.label :annual_rate
        = f.number_field :annual_rate, step: :any, class: 'form-control'
      = f.submit 'Save', class: 'btn btn-success'

app/views/users/shared/_error_messages.html.haml
- if resource.errors.any?
  #error_explanation
    %h2
      = I18n.t("errors.messages.not_saved",                 |
        count: resource.errors.count,                       |
        resource: resource.class.model_name.human.downcase) |
    %ul
      - resource.errors.full_messages.each do |message|
        %li= message

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/